# Generated by Django 4.1.7 on 2023-07-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='installation_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=20, null=True)),
                ('lon', models.FloatField(max_length=20, null=True)),
                ('debit', models.FloatField(default=0.0, max_length=8)),
                ('measure', models.CharField(choices=[('Ko', 'Ko'), ('Mo', 'Mo'), ('Go', 'Go')], default='Mo', max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
