# Generated by Django 4.1.7 on 2023-07-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation_information',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
