# Generated by Django 4.1.7 on 2023-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0002_installation_information_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installation_information',
            old_name='measure',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='installation_information',
            old_name='debit',
            new_name='value',
        ),
        migrations.AddField(
            model_name='installation_information',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
