# Generated by Django 4.1.7 on 2023-08-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0003_rename_measure_installation_information_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='forfait_entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=20, null=True)),
                ('nom_produit', models.CharField(max_length=30, null=True)),
                ('debit', models.CharField(max_length=10, null=True)),
                ('volume', models.CharField(max_length=10, null=True)),
                ('validite', models.CharField(max_length=30, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='forfait_residentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=20, null=True)),
                ('nom_produit', models.CharField(max_length=30, null=True)),
                ('debit', models.CharField(max_length=10, null=True)),
                ('volume_jour', models.CharField(max_length=10, null=True)),
                ('volume_nuit', models.CharField(max_length=50, null=True)),
                ('validite', models.CharField(max_length=30, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forfait_entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.forfait_entreprise')),
                ('forfait_residentiel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.forfait_residentiel')),
            ],
        ),
        migrations.AddField(
            model_name='installation_information',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.service'),
        ),
    ]
