# Generated by Django 4.1.7 on 2023-08-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0004_forfait_entreprise_forfait_residentiel_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation_information',
            name='unit',
        ),
        migrations.AddField(
            model_name='installation_information',
            name='activer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installation_information',
            name='cle_activation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
