# Generated by Django 4.1.7 on 2023-08-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0005_remove_installation_information_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation_information',
            name='service',
        ),
        migrations.RemoveField(
            model_name='installation_information',
            name='value',
        ),
        migrations.AddField(
            model_name='installation_information',
            name='forfait_entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.forfait_entreprise'),
        ),
        migrations.AddField(
            model_name='installation_information',
            name='forfait_residentiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.forfait_residentiel'),
        ),
        migrations.AddField(
            model_name='installation_information',
            name='type_forfait',
            field=models.CharField(choices=[('Forfait Résidentiel', 'forfait résidentiel'), ('Forfait Entreprise', 'forfait entreprise')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forfait_entreprise',
            name='debit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forfait_entreprise',
            name='nom_produit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forfait_entreprise',
            name='volume',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forfait_residentiel',
            name='debit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forfait_residentiel',
            name='nom_produit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forfait_residentiel',
            name='volume_jour',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
