# Generated by Django 4.1.7 on 2023-10-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0011_alter_installation_information_forfait_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='nom_service',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='installation_information',
            name='activer',
        ),
        migrations.RemoveField(
            model_name='installation_information',
            name='cle_activation',
        ),
        migrations.RemoveField(
            model_name='installation_information',
            name='forfait',
        ),
        migrations.RemoveField(
            model_name='installation_information',
            name='service',
        ),
        migrations.RemoveField(
            model_name='installation_information',
            name='status',
        ),
        migrations.AlterField(
            model_name='service',
            name='forfait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.forfait'),
        ),
        migrations.CreateModel(
            name='validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('forfait', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.forfait')),
                ('information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.installation_information')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.service')),
            ],
        ),
        migrations.CreateModel(
            name='activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_activation', models.CharField(max_length=100, null=True)),
                ('activer', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bka.installation_information')),
            ],
        ),
    ]
