# Generated by Django 4.1.7 on 2023-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0012_rename_nom_service_service_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='status',
            new_name='activer',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='activer',
        ),
        migrations.AddField(
            model_name='installation_information',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
