# Generated by Django 4.1.7 on 2023-10-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0013_rename_status_validation_activer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='nom',
            new_name='nom_service',
        ),
    ]
