# Generated by Django 4.1.7 on 2023-10-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bka', '0014_rename_nom_service_nom_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='information',
            new_name='customer',
        ),
    ]
